// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth/v1/role.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRoleRequest) Reset() {
	*x = PageRoleRequest{}
	mi := &file_auth_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRoleRequest) ProtoMessage() {}

func (x *PageRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRoleRequest.ProtoReflect.Descriptor instead.
func (*PageRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *PageRoleRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type PageRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Roles         []*RoleInfo            `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRoleResponse) Reset() {
	*x = PageRoleResponse{}
	mi := &file_auth_v1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRoleResponse) ProtoMessage() {}

func (x *PageRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRoleResponse.ProtoReflect.Descriptor instead.
func (*PageRoleResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_role_proto_rawDescGZIP(), []int{1}
}

func (x *PageRoleResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageRoleResponse) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 角色相关消息
type RoleInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code              string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PermissionSpaceId int64                  `protobuf:"varint,4,opt,name=permission_space_id,json=permissionSpaceId,proto3" json:"permission_space_id,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_auth_v1_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_auth_v1_role_proto_rawDescGZIP(), []int{2}
}

func (x *RoleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetPermissionSpaceId() int64 {
	if x != nil {
		return x.PermissionSpaceId
	}
	return 0
}

func (x *RoleInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RoleInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateRoleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PermissionSpaceId int64                  `protobuf:"varint,3,opt,name=permission_space_id,json=permissionSpaceId,proto3" json:"permission_space_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_auth_v1_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_role_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetPermissionSpaceId() int64 {
	if x != nil {
		return x.PermissionSpaceId
	}
	return 0
}

type UpdateRoleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code              string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PermissionSpaceId int64                  `protobuf:"varint,4,opt,name=permission_space_id,json=permissionSpaceId,proto3" json:"permission_space_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_auth_v1_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_role_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetPermissionSpaceId() int64 {
	if x != nil {
		return x.PermissionSpaceId
	}
	return 0
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_auth_v1_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_role_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_auth_v1_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_role_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_auth_v1_role_proto protoreflect.FileDescriptor

const file_auth_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/role.proto\x12\aauth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x13auth/v1/basic.proto\";\n" +
	"\x0fPageRoleRequest\x12(\n" +
	"\x04page\x18\x01 \x01(\v2\x14.auth.v1.PageRequestR\x04page\"Q\n" +
	"\x10PageRoleResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12'\n" +
	"\x05roles\x18\x02 \x03(\v2\x11.auth.v1.RoleInfoR\x05roles\"\xb0\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\x13permission_space_id\x18\x04 \x01(\x03R\x11permissionSpaceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"k\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x13permission_space_id\x18\x03 \x01(\x03R\x11permissionSpaceId\"{\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\x13permission_space_id\x18\x04 \x01(\x03R\x11permissionSpaceId\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\x94\x03\n" +
	"\x04Role\x12S\n" +
	"\bPageList\x12\x18.auth.v1.PageRoleRequest\x1a\x19.auth.v1.PageRoleResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/role/list\x12E\n" +
	"\x03Get\x12\x17.auth.v1.GetRoleRequest\x1a\x11.auth.v1.RoleInfo\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/role/{id}\x12I\n" +
	"\x06Create\x12\x1a.auth.v1.CreateRoleRequest\x1a\x11.auth.v1.RoleInfo\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/role\x12S\n" +
	"\x06Update\x12\x1a.auth.v1.UpdateRoleRequest\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\x1a\n" +
	"/role/{id}\x12P\n" +
	"\x06Delete\x12\x1a.auth.v1.DeleteRoleRequest\x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/role/{id}BC\n" +
	"\x16dev.kratos.api.auth.v1B\vAuthProtoV1P\x01Z\x1aheytom-auth/api/auth/v1;v1b\x06proto3"

var (
	file_auth_v1_role_proto_rawDescOnce sync.Once
	file_auth_v1_role_proto_rawDescData []byte
)

func file_auth_v1_role_proto_rawDescGZIP() []byte {
	file_auth_v1_role_proto_rawDescOnce.Do(func() {
		file_auth_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_role_proto_rawDesc), len(file_auth_v1_role_proto_rawDesc)))
	})
	return file_auth_v1_role_proto_rawDescData
}

var file_auth_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_v1_role_proto_goTypes = []any{
	(*PageRoleRequest)(nil),   // 0: auth.v1.PageRoleRequest
	(*PageRoleResponse)(nil),  // 1: auth.v1.PageRoleResponse
	(*RoleInfo)(nil),          // 2: auth.v1.RoleInfo
	(*CreateRoleRequest)(nil), // 3: auth.v1.CreateRoleRequest
	(*UpdateRoleRequest)(nil), // 4: auth.v1.UpdateRoleRequest
	(*DeleteRoleRequest)(nil), // 5: auth.v1.DeleteRoleRequest
	(*GetRoleRequest)(nil),    // 6: auth.v1.GetRoleRequest
	(*PageRequest)(nil),       // 7: auth.v1.PageRequest
	(*emptypb.Empty)(nil),     // 8: google.protobuf.Empty
}
var file_auth_v1_role_proto_depIdxs = []int32{
	7, // 0: auth.v1.PageRoleRequest.page:type_name -> auth.v1.PageRequest
	2, // 1: auth.v1.PageRoleResponse.roles:type_name -> auth.v1.RoleInfo
	0, // 2: auth.v1.Role.PageList:input_type -> auth.v1.PageRoleRequest
	6, // 3: auth.v1.Role.Get:input_type -> auth.v1.GetRoleRequest
	3, // 4: auth.v1.Role.Create:input_type -> auth.v1.CreateRoleRequest
	4, // 5: auth.v1.Role.Update:input_type -> auth.v1.UpdateRoleRequest
	5, // 6: auth.v1.Role.Delete:input_type -> auth.v1.DeleteRoleRequest
	1, // 7: auth.v1.Role.PageList:output_type -> auth.v1.PageRoleResponse
	2, // 8: auth.v1.Role.Get:output_type -> auth.v1.RoleInfo
	2, // 9: auth.v1.Role.Create:output_type -> auth.v1.RoleInfo
	8, // 10: auth.v1.Role.Update:output_type -> google.protobuf.Empty
	8, // 11: auth.v1.Role.Delete:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_v1_role_proto_init() }
func file_auth_v1_role_proto_init() {
	if File_auth_v1_role_proto != nil {
		return
	}
	file_auth_v1_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_role_proto_rawDesc), len(file_auth_v1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_role_proto_goTypes,
		DependencyIndexes: file_auth_v1_role_proto_depIdxs,
		MessageInfos:      file_auth_v1_role_proto_msgTypes,
	}.Build()
	File_auth_v1_role_proto = out.File
	file_auth_v1_role_proto_goTypes = nil
	file_auth_v1_role_proto_depIdxs = nil
}
