// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth/v1/application.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 应用相关消息
type ApplicationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AppKey        string                 `protobuf:"bytes,4,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	AppSecret     string                 `protobuf:"bytes,5,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,6,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationInfo) Reset() {
	*x = ApplicationInfo{}
	mi := &file_auth_v1_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationInfo) ProtoMessage() {}

func (x *ApplicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationInfo.ProtoReflect.Descriptor instead.
func (*ApplicationInfo) Descriptor() ([]byte, []int) {
	return file_auth_v1_application_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApplicationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApplicationInfo) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *ApplicationInfo) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *ApplicationInfo) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *ApplicationInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ApplicationInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type DeleteApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationRequest) Reset() {
	*x = DeleteApplicationRequest{}
	mi := &file_auth_v1_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationRequest) ProtoMessage() {}

func (x *DeleteApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_application_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteApplicationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,3,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_auth_v1_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_application_proto_rawDescGZIP(), []int{2}
}

func (x *CreateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApplicationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateApplicationRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type UpdateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_auth_v1_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_application_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateApplicationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateApplicationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateApplicationRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type GetApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_auth_v1_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_application_proto_rawDescGZIP(), []int{4}
}

func (x *GetApplicationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PageApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageApplicationRequest) Reset() {
	*x = PageApplicationRequest{}
	mi := &file_auth_v1_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageApplicationRequest) ProtoMessage() {}

func (x *PageApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageApplicationRequest.ProtoReflect.Descriptor instead.
func (*PageApplicationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_application_proto_rawDescGZIP(), []int{5}
}

func (x *PageApplicationRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type PageApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Applications  []*ApplicationInfo     `protobuf:"bytes,2,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageApplicationResponse) Reset() {
	*x = PageApplicationResponse{}
	mi := &file_auth_v1_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageApplicationResponse) ProtoMessage() {}

func (x *PageApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageApplicationResponse.ProtoReflect.Descriptor instead.
func (*PageApplicationResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_application_proto_rawDescGZIP(), []int{6}
}

func (x *PageApplicationResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageApplicationResponse) GetApplications() []*ApplicationInfo {
	if x != nil {
		return x.Applications
	}
	return nil
}

var File_auth_v1_application_proto protoreflect.FileDescriptor

const file_auth_v1_application_proto_rawDesc = "" +
	"\n" +
	"\x19auth/v1/application.proto\x12\aauth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13auth/v1/basic.proto\"\xf0\x01\n" +
	"\x0fApplicationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\aapp_key\x18\x04 \x01(\tR\x06appKey\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x05 \x01(\tR\tappSecret\x12!\n" +
	"\fcallback_url\x18\x06 \x01(\tR\vcallbackUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"*\n" +
	"\x18DeleteApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"s\n" +
	"\x18CreateApplicationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fcallback_url\x18\x03 \x01(\tR\vcallbackUrl\"\x83\x01\n" +
	"\x18UpdateApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fcallback_url\x18\x04 \x01(\tR\vcallbackUrl\"'\n" +
	"\x15GetApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"B\n" +
	"\x16PageApplicationRequest\x12(\n" +
	"\x04page\x18\x01 \x01(\v2\x14.auth.v1.PageRequestR\x04page\"m\n" +
	"\x17PageApplicationResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12<\n" +
	"\fapplications\x18\x02 \x03(\v2\x18.auth.v1.ApplicationInfoR\fapplications2\xee\x02\n" +
	"\vApplication\x12M\n" +
	"\bPageList\x12\x1f.auth.v1.PageApplicationRequest\x1a .auth.v1.PageApplicationResponse\x12?\n" +
	"\x03Get\x12\x1e.auth.v1.GetApplicationRequest\x1a\x18.auth.v1.ApplicationInfo\x12E\n" +
	"\x06Create\x12!.auth.v1.CreateApplicationRequest\x1a\x18.auth.v1.ApplicationInfo\x12C\n" +
	"\x06Update\x12!.auth.v1.UpdateApplicationRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x06Delete\x12!.auth.v1.DeleteApplicationRequest\x1a\x16.google.protobuf.EmptyBC\n" +
	"\x16dev.kratos.api.auth.v1B\vAuthProtoV1P\x01Z\x1aheytom-auth/api/auth/v1;v1b\x06proto3"

var (
	file_auth_v1_application_proto_rawDescOnce sync.Once
	file_auth_v1_application_proto_rawDescData []byte
)

func file_auth_v1_application_proto_rawDescGZIP() []byte {
	file_auth_v1_application_proto_rawDescOnce.Do(func() {
		file_auth_v1_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_application_proto_rawDesc), len(file_auth_v1_application_proto_rawDesc)))
	})
	return file_auth_v1_application_proto_rawDescData
}

var file_auth_v1_application_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_v1_application_proto_goTypes = []any{
	(*ApplicationInfo)(nil),          // 0: auth.v1.ApplicationInfo
	(*DeleteApplicationRequest)(nil), // 1: auth.v1.DeleteApplicationRequest
	(*CreateApplicationRequest)(nil), // 2: auth.v1.CreateApplicationRequest
	(*UpdateApplicationRequest)(nil), // 3: auth.v1.UpdateApplicationRequest
	(*GetApplicationRequest)(nil),    // 4: auth.v1.GetApplicationRequest
	(*PageApplicationRequest)(nil),   // 5: auth.v1.PageApplicationRequest
	(*PageApplicationResponse)(nil),  // 6: auth.v1.PageApplicationResponse
	(*PageRequest)(nil),              // 7: auth.v1.PageRequest
	(*emptypb.Empty)(nil),            // 8: google.protobuf.Empty
}
var file_auth_v1_application_proto_depIdxs = []int32{
	7, // 0: auth.v1.PageApplicationRequest.page:type_name -> auth.v1.PageRequest
	0, // 1: auth.v1.PageApplicationResponse.applications:type_name -> auth.v1.ApplicationInfo
	5, // 2: auth.v1.Application.PageList:input_type -> auth.v1.PageApplicationRequest
	4, // 3: auth.v1.Application.Get:input_type -> auth.v1.GetApplicationRequest
	2, // 4: auth.v1.Application.Create:input_type -> auth.v1.CreateApplicationRequest
	3, // 5: auth.v1.Application.Update:input_type -> auth.v1.UpdateApplicationRequest
	1, // 6: auth.v1.Application.Delete:input_type -> auth.v1.DeleteApplicationRequest
	6, // 7: auth.v1.Application.PageList:output_type -> auth.v1.PageApplicationResponse
	0, // 8: auth.v1.Application.Get:output_type -> auth.v1.ApplicationInfo
	0, // 9: auth.v1.Application.Create:output_type -> auth.v1.ApplicationInfo
	8, // 10: auth.v1.Application.Update:output_type -> google.protobuf.Empty
	8, // 11: auth.v1.Application.Delete:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_v1_application_proto_init() }
func file_auth_v1_application_proto_init() {
	if File_auth_v1_application_proto != nil {
		return
	}
	file_auth_v1_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_application_proto_rawDesc), len(file_auth_v1_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_application_proto_goTypes,
		DependencyIndexes: file_auth_v1_application_proto_depIdxs,
		MessageInfos:      file_auth_v1_application_proto_msgTypes,
	}.Build()
	File_auth_v1_application_proto = out.File
	file_auth_v1_application_proto_goTypes = nil
	file_auth_v1_application_proto_depIdxs = nil
}
