// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth/v1/basic.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分页请求
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageIndex     int32                  `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_auth_v1_basic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_basic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_basic_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_auth_v1_basic_proto protoreflect.FileDescriptor

const file_auth_v1_basic_proto_rawDesc = "" +
	"\n" +
	"\x13auth/v1/basic.proto\x12\aauth.v1\x1a\x1bgoogle/protobuf/empty.proto\"I\n" +
	"\vPageRequest\x12\x1d\n" +
	"\n" +
	"page_index\x18\x01 \x01(\x05R\tpageIndex\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSizeBC\n" +
	"\x16dev.kratos.api.auth.v1B\vAuthProtoV1P\x01Z\x1aheytom-auth/api/auth/v1;v1b\x06proto3"

var (
	file_auth_v1_basic_proto_rawDescOnce sync.Once
	file_auth_v1_basic_proto_rawDescData []byte
)

func file_auth_v1_basic_proto_rawDescGZIP() []byte {
	file_auth_v1_basic_proto_rawDescOnce.Do(func() {
		file_auth_v1_basic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_basic_proto_rawDesc), len(file_auth_v1_basic_proto_rawDesc)))
	})
	return file_auth_v1_basic_proto_rawDescData
}

var file_auth_v1_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_v1_basic_proto_goTypes = []any{
	(*PageRequest)(nil), // 0: auth.v1.PageRequest
}
var file_auth_v1_basic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_basic_proto_init() }
func file_auth_v1_basic_proto_init() {
	if File_auth_v1_basic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_basic_proto_rawDesc), len(file_auth_v1_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_basic_proto_goTypes,
		DependencyIndexes: file_auth_v1_basic_proto_depIdxs,
		MessageInfos:      file_auth_v1_basic_proto_msgTypes,
	}.Build()
	File_auth_v1_basic_proto = out.File
	file_auth_v1_basic_proto_goTypes = nil
	file_auth_v1_basic_proto_depIdxs = nil
}
