// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth/v1/organization.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 组织相关消息
type OrganizationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationInfo) Reset() {
	*x = OrganizationInfo{}
	mi := &file_auth_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationInfo) ProtoMessage() {}

func (x *OrganizationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationInfo.ProtoReflect.Descriptor instead.
func (*OrganizationInfo) Descriptor() ([]byte, []int) {
	return file_auth_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrganizationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OrganizationInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *OrganizationInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrganizationInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OrganizationInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type DeleteOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationRequest) Reset() {
	*x = DeleteOrganizationRequest{}
	mi := &file_auth_v1_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationRequest) ProtoMessage() {}

func (x *DeleteOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteOrganizationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_auth_v1_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateOrganizationRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateOrganizationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_auth_v1_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_organization_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateOrganizationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UpdateOrganizationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_auth_v1_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_organization_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrganizationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PageOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageOrganizationRequest) Reset() {
	*x = PageOrganizationRequest{}
	mi := &file_auth_v1_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageOrganizationRequest) ProtoMessage() {}

func (x *PageOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageOrganizationRequest.ProtoReflect.Descriptor instead.
func (*PageOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_organization_proto_rawDescGZIP(), []int{5}
}

func (x *PageOrganizationRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type PageOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Organizations []*OrganizationInfo    `protobuf:"bytes,2,rep,name=organizations,proto3" json:"organizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageOrganizationResponse) Reset() {
	*x = PageOrganizationResponse{}
	mi := &file_auth_v1_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageOrganizationResponse) ProtoMessage() {}

func (x *PageOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageOrganizationResponse.ProtoReflect.Descriptor instead.
func (*PageOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_organization_proto_rawDescGZIP(), []int{6}
}

func (x *PageOrganizationResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageOrganizationResponse) GetOrganizations() []*OrganizationInfo {
	if x != nil {
		return x.Organizations
	}
	return nil
}

var File_auth_v1_organization_proto protoreflect.FileDescriptor

const file_auth_v1_organization_proto_rawDesc = "" +
	"\n" +
	"\x1aauth/v1/organization.proto\x12\aauth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13auth/v1/basic.proto\"\xc7\x01\n" +
	"\x10OrganizationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"+\n" +
	"\x19DeleteOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x82\x01\n" +
	"\x19CreateOrganizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x92\x01\n" +
	"\x19UpdateOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"(\n" +
	"\x16GetOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x17PageOrganizationRequest\x12(\n" +
	"\x04page\x18\x01 \x01(\v2\x14.auth.v1.PageRequestR\x04page\"q\n" +
	"\x18PageOrganizationResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12?\n" +
	"\rorganizations\x18\x02 \x03(\v2\x19.auth.v1.OrganizationInfoR\rorganizations2\xf7\x02\n" +
	"\fOrganization\x12O\n" +
	"\bPageList\x12 .auth.v1.PageOrganizationRequest\x1a!.auth.v1.PageOrganizationResponse\x12A\n" +
	"\x03Get\x12\x1f.auth.v1.GetOrganizationRequest\x1a\x19.auth.v1.OrganizationInfo\x12G\n" +
	"\x06Create\x12\".auth.v1.CreateOrganizationRequest\x1a\x19.auth.v1.OrganizationInfo\x12D\n" +
	"\x06Update\x12\".auth.v1.UpdateOrganizationRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x06Delete\x12\".auth.v1.DeleteOrganizationRequest\x1a\x16.google.protobuf.EmptyBC\n" +
	"\x16dev.kratos.api.auth.v1B\vAuthProtoV1P\x01Z\x1aheytom-auth/api/auth/v1;v1b\x06proto3"

var (
	file_auth_v1_organization_proto_rawDescOnce sync.Once
	file_auth_v1_organization_proto_rawDescData []byte
)

func file_auth_v1_organization_proto_rawDescGZIP() []byte {
	file_auth_v1_organization_proto_rawDescOnce.Do(func() {
		file_auth_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_organization_proto_rawDesc), len(file_auth_v1_organization_proto_rawDesc)))
	})
	return file_auth_v1_organization_proto_rawDescData
}

var file_auth_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_v1_organization_proto_goTypes = []any{
	(*OrganizationInfo)(nil),          // 0: auth.v1.OrganizationInfo
	(*DeleteOrganizationRequest)(nil), // 1: auth.v1.DeleteOrganizationRequest
	(*CreateOrganizationRequest)(nil), // 2: auth.v1.CreateOrganizationRequest
	(*UpdateOrganizationRequest)(nil), // 3: auth.v1.UpdateOrganizationRequest
	(*GetOrganizationRequest)(nil),    // 4: auth.v1.GetOrganizationRequest
	(*PageOrganizationRequest)(nil),   // 5: auth.v1.PageOrganizationRequest
	(*PageOrganizationResponse)(nil),  // 6: auth.v1.PageOrganizationResponse
	(*PageRequest)(nil),               // 7: auth.v1.PageRequest
	(*emptypb.Empty)(nil),             // 8: google.protobuf.Empty
}
var file_auth_v1_organization_proto_depIdxs = []int32{
	7, // 0: auth.v1.PageOrganizationRequest.page:type_name -> auth.v1.PageRequest
	0, // 1: auth.v1.PageOrganizationResponse.organizations:type_name -> auth.v1.OrganizationInfo
	5, // 2: auth.v1.Organization.PageList:input_type -> auth.v1.PageOrganizationRequest
	4, // 3: auth.v1.Organization.Get:input_type -> auth.v1.GetOrganizationRequest
	2, // 4: auth.v1.Organization.Create:input_type -> auth.v1.CreateOrganizationRequest
	3, // 5: auth.v1.Organization.Update:input_type -> auth.v1.UpdateOrganizationRequest
	1, // 6: auth.v1.Organization.Delete:input_type -> auth.v1.DeleteOrganizationRequest
	6, // 7: auth.v1.Organization.PageList:output_type -> auth.v1.PageOrganizationResponse
	0, // 8: auth.v1.Organization.Get:output_type -> auth.v1.OrganizationInfo
	0, // 9: auth.v1.Organization.Create:output_type -> auth.v1.OrganizationInfo
	8, // 10: auth.v1.Organization.Update:output_type -> google.protobuf.Empty
	8, // 11: auth.v1.Organization.Delete:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_v1_organization_proto_init() }
func file_auth_v1_organization_proto_init() {
	if File_auth_v1_organization_proto != nil {
		return
	}
	file_auth_v1_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_organization_proto_rawDesc), len(file_auth_v1_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_organization_proto_goTypes,
		DependencyIndexes: file_auth_v1_organization_proto_depIdxs,
		MessageInfos:      file_auth_v1_organization_proto_msgTypes,
	}.Build()
	File_auth_v1_organization_proto = out.File
	file_auth_v1_organization_proto_goTypes = nil
	file_auth_v1_organization_proto_depIdxs = nil
}
