// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.31.1
// source: auth/v1/organization.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOrganizationCreate = "/auth.v1.Organization/Create"
const OperationOrganizationDelete = "/auth.v1.Organization/Delete"
const OperationOrganizationGet = "/auth.v1.Organization/Get"
const OperationOrganizationPageList = "/auth.v1.Organization/PageList"
const OperationOrganizationUpdate = "/auth.v1.Organization/Update"

type OrganizationHTTPServer interface {
	Create(context.Context, *CreateOrganizationRequest) (*OrganizationInfo, error)
	Delete(context.Context, *DeleteOrganizationRequest) (*emptypb.Empty, error)
	Get(context.Context, *GetOrganizationRequest) (*OrganizationInfo, error)
	PageList(context.Context, *PageOrganizationRequest) (*PageOrganizationResponse, error)
	Update(context.Context, *UpdateOrganizationRequest) (*emptypb.Empty, error)
}

func RegisterOrganizationHTTPServer(s *http.Server, srv OrganizationHTTPServer) {
	r := s.Route("/")
	r.GET("/organization/list", _Organization_PageList1_HTTP_Handler(srv))
	r.GET("/organization/{id}", _Organization_Get1_HTTP_Handler(srv))
	r.POST("/organization", _Organization_Create1_HTTP_Handler(srv))
	r.PUT("/organization/{id}", _Organization_Update1_HTTP_Handler(srv))
	r.DELETE("/organization/{id}", _Organization_Delete1_HTTP_Handler(srv))
}

func _Organization_PageList1_HTTP_Handler(srv OrganizationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageOrganizationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrganizationPageList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PageList(ctx, req.(*PageOrganizationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PageOrganizationResponse)
		return ctx.Result(200, reply)
	}
}

func _Organization_Get1_HTTP_Handler(srv OrganizationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrganizationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrganizationGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*GetOrganizationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrganizationInfo)
		return ctx.Result(200, reply)
	}
}

func _Organization_Create1_HTTP_Handler(srv OrganizationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOrganizationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrganizationCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*CreateOrganizationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrganizationInfo)
		return ctx.Result(200, reply)
	}
}

func _Organization_Update1_HTTP_Handler(srv OrganizationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateOrganizationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrganizationUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UpdateOrganizationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Organization_Delete1_HTTP_Handler(srv OrganizationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteOrganizationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrganizationDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*DeleteOrganizationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type OrganizationHTTPClient interface {
	Create(ctx context.Context, req *CreateOrganizationRequest, opts ...http.CallOption) (rsp *OrganizationInfo, err error)
	Delete(ctx context.Context, req *DeleteOrganizationRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	Get(ctx context.Context, req *GetOrganizationRequest, opts ...http.CallOption) (rsp *OrganizationInfo, err error)
	PageList(ctx context.Context, req *PageOrganizationRequest, opts ...http.CallOption) (rsp *PageOrganizationResponse, err error)
	Update(ctx context.Context, req *UpdateOrganizationRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type OrganizationHTTPClientImpl struct {
	cc *http.Client
}

func NewOrganizationHTTPClient(client *http.Client) OrganizationHTTPClient {
	return &OrganizationHTTPClientImpl{client}
}

func (c *OrganizationHTTPClientImpl) Create(ctx context.Context, in *CreateOrganizationRequest, opts ...http.CallOption) (*OrganizationInfo, error) {
	var out OrganizationInfo
	pattern := "/organization"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrganizationCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrganizationHTTPClientImpl) Delete(ctx context.Context, in *DeleteOrganizationRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/organization/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrganizationDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrganizationHTTPClientImpl) Get(ctx context.Context, in *GetOrganizationRequest, opts ...http.CallOption) (*OrganizationInfo, error) {
	var out OrganizationInfo
	pattern := "/organization/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrganizationGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrganizationHTTPClientImpl) PageList(ctx context.Context, in *PageOrganizationRequest, opts ...http.CallOption) (*PageOrganizationResponse, error) {
	var out PageOrganizationResponse
	pattern := "/organization/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrganizationPageList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrganizationHTTPClientImpl) Update(ctx context.Context, in *UpdateOrganizationRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/organization/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrganizationUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
