// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.31.1
// source: auth/v1/policy.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPolicyCreate = "/auth.v1.Policy/Create"
const OperationPolicyDelete = "/auth.v1.Policy/Delete"
const OperationPolicyGet = "/auth.v1.Policy/Get"
const OperationPolicyPageList = "/auth.v1.Policy/PageList"
const OperationPolicyUpdate = "/auth.v1.Policy/Update"

type PolicyHTTPServer interface {
	Create(context.Context, *CreatePolicyRequest) (*PolicyInfo, error)
	Delete(context.Context, *DeletePolicyRequest) (*emptypb.Empty, error)
	Get(context.Context, *GetPolicyRequest) (*PolicyInfo, error)
	PageList(context.Context, *PagePolicyRequest) (*PagePolicyResponse, error)
	Update(context.Context, *UpdatePolicyRequest) (*emptypb.Empty, error)
}

func RegisterPolicyHTTPServer(s *http.Server, srv PolicyHTTPServer) {
	r := s.Route("/")
	r.GET("/policy/list", _Policy_PageList1_HTTP_Handler(srv))
	r.GET("/policy/{id}", _Policy_Get1_HTTP_Handler(srv))
	r.POST("/policy", _Policy_Create1_HTTP_Handler(srv))
	r.PUT("/policy/{id}", _Policy_Update1_HTTP_Handler(srv))
	r.DELETE("/policy/{id}", _Policy_Delete1_HTTP_Handler(srv))
}

func _Policy_PageList1_HTTP_Handler(srv PolicyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PagePolicyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPolicyPageList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PageList(ctx, req.(*PagePolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PagePolicyResponse)
		return ctx.Result(200, reply)
	}
}

func _Policy_Get1_HTTP_Handler(srv PolicyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPolicyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPolicyGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*GetPolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PolicyInfo)
		return ctx.Result(200, reply)
	}
}

func _Policy_Create1_HTTP_Handler(srv PolicyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePolicyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPolicyCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*CreatePolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PolicyInfo)
		return ctx.Result(200, reply)
	}
}

func _Policy_Update1_HTTP_Handler(srv PolicyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePolicyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPolicyUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UpdatePolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Policy_Delete1_HTTP_Handler(srv PolicyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePolicyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPolicyDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*DeletePolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type PolicyHTTPClient interface {
	Create(ctx context.Context, req *CreatePolicyRequest, opts ...http.CallOption) (rsp *PolicyInfo, err error)
	Delete(ctx context.Context, req *DeletePolicyRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	Get(ctx context.Context, req *GetPolicyRequest, opts ...http.CallOption) (rsp *PolicyInfo, err error)
	PageList(ctx context.Context, req *PagePolicyRequest, opts ...http.CallOption) (rsp *PagePolicyResponse, err error)
	Update(ctx context.Context, req *UpdatePolicyRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type PolicyHTTPClientImpl struct {
	cc *http.Client
}

func NewPolicyHTTPClient(client *http.Client) PolicyHTTPClient {
	return &PolicyHTTPClientImpl{client}
}

func (c *PolicyHTTPClientImpl) Create(ctx context.Context, in *CreatePolicyRequest, opts ...http.CallOption) (*PolicyInfo, error) {
	var out PolicyInfo
	pattern := "/policy"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPolicyCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PolicyHTTPClientImpl) Delete(ctx context.Context, in *DeletePolicyRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/policy/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPolicyDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PolicyHTTPClientImpl) Get(ctx context.Context, in *GetPolicyRequest, opts ...http.CallOption) (*PolicyInfo, error) {
	var out PolicyInfo
	pattern := "/policy/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPolicyGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PolicyHTTPClientImpl) PageList(ctx context.Context, in *PagePolicyRequest, opts ...http.CallOption) (*PagePolicyResponse, error) {
	var out PagePolicyResponse
	pattern := "/policy/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPolicyPageList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PolicyHTTPClientImpl) Update(ctx context.Context, in *UpdatePolicyRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/policy/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPolicyUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
