// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth/v1/policy.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 策略相关消息
type PolicyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyInfo) Reset() {
	*x = PolicyInfo{}
	mi := &file_auth_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyInfo) ProtoMessage() {}

func (x *PolicyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyInfo.ProtoReflect.Descriptor instead.
func (*PolicyInfo) Descriptor() ([]byte, []int) {
	return file_auth_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PolicyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PolicyInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolicyInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PolicyInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type DeletePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_auth_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *DeletePolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_auth_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePolicyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyRequest) Reset() {
	*x = UpdatePolicyRequest{}
	mi := &file_auth_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyRequest) ProtoMessage() {}

func (x *UpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePolicyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_auth_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *GetPolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PagePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagePolicyRequest) Reset() {
	*x = PagePolicyRequest{}
	mi := &file_auth_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagePolicyRequest) ProtoMessage() {}

func (x *PagePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagePolicyRequest.ProtoReflect.Descriptor instead.
func (*PagePolicyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *PagePolicyRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type PagePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Policies      []*PolicyInfo          `protobuf:"bytes,2,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagePolicyResponse) Reset() {
	*x = PagePolicyResponse{}
	mi := &file_auth_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagePolicyResponse) ProtoMessage() {}

func (x *PagePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagePolicyResponse.ProtoReflect.Descriptor instead.
func (*PagePolicyResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *PagePolicyResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PagePolicyResponse) GetPolicies() []*PolicyInfo {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_auth_v1_policy_proto protoreflect.FileDescriptor

const file_auth_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x14auth/v1/policy.proto\x12\aauth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x13auth/v1/basic.proto\"\xa4\x01\n" +
	"\n" +
	"PolicyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"%\n" +
	"\x13DeletePolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"_\n" +
	"\x13CreatePolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"o\n" +
	"\x13UpdatePolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\"\n" +
	"\x10GetPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x11PagePolicyRequest\x12(\n" +
	"\x04page\x18\x01 \x01(\v2\x14.auth.v1.PageRequestR\x04page\"[\n" +
	"\x12PagePolicyResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12/\n" +
	"\bpolicies\x18\x02 \x03(\v2\x13.auth.v1.PolicyInfoR\bpolicies2\xb0\x03\n" +
	"\x06Policy\x12Y\n" +
	"\bPageList\x12\x1a.auth.v1.PagePolicyRequest\x1a\x1b.auth.v1.PagePolicyResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/policy/list\x12K\n" +
	"\x03Get\x12\x19.auth.v1.GetPolicyRequest\x1a\x13.auth.v1.PolicyInfo\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/policy/{id}\x12O\n" +
	"\x06Create\x12\x1c.auth.v1.CreatePolicyRequest\x1a\x13.auth.v1.PolicyInfo\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/policy\x12W\n" +
	"\x06Update\x12\x1c.auth.v1.UpdatePolicyRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/policy/{id}\x12T\n" +
	"\x06Delete\x12\x1c.auth.v1.DeletePolicyRequest\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/policy/{id}BC\n" +
	"\x16dev.kratos.api.auth.v1B\vAuthProtoV1P\x01Z\x1aheytom-auth/api/auth/v1;v1b\x06proto3"

var (
	file_auth_v1_policy_proto_rawDescOnce sync.Once
	file_auth_v1_policy_proto_rawDescData []byte
)

func file_auth_v1_policy_proto_rawDescGZIP() []byte {
	file_auth_v1_policy_proto_rawDescOnce.Do(func() {
		file_auth_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_policy_proto_rawDesc), len(file_auth_v1_policy_proto_rawDesc)))
	})
	return file_auth_v1_policy_proto_rawDescData
}

var file_auth_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_v1_policy_proto_goTypes = []any{
	(*PolicyInfo)(nil),          // 0: auth.v1.PolicyInfo
	(*DeletePolicyRequest)(nil), // 1: auth.v1.DeletePolicyRequest
	(*CreatePolicyRequest)(nil), // 2: auth.v1.CreatePolicyRequest
	(*UpdatePolicyRequest)(nil), // 3: auth.v1.UpdatePolicyRequest
	(*GetPolicyRequest)(nil),    // 4: auth.v1.GetPolicyRequest
	(*PagePolicyRequest)(nil),   // 5: auth.v1.PagePolicyRequest
	(*PagePolicyResponse)(nil),  // 6: auth.v1.PagePolicyResponse
	(*PageRequest)(nil),         // 7: auth.v1.PageRequest
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_auth_v1_policy_proto_depIdxs = []int32{
	7, // 0: auth.v1.PagePolicyRequest.page:type_name -> auth.v1.PageRequest
	0, // 1: auth.v1.PagePolicyResponse.policies:type_name -> auth.v1.PolicyInfo
	5, // 2: auth.v1.Policy.PageList:input_type -> auth.v1.PagePolicyRequest
	4, // 3: auth.v1.Policy.Get:input_type -> auth.v1.GetPolicyRequest
	2, // 4: auth.v1.Policy.Create:input_type -> auth.v1.CreatePolicyRequest
	3, // 5: auth.v1.Policy.Update:input_type -> auth.v1.UpdatePolicyRequest
	1, // 6: auth.v1.Policy.Delete:input_type -> auth.v1.DeletePolicyRequest
	6, // 7: auth.v1.Policy.PageList:output_type -> auth.v1.PagePolicyResponse
	0, // 8: auth.v1.Policy.Get:output_type -> auth.v1.PolicyInfo
	0, // 9: auth.v1.Policy.Create:output_type -> auth.v1.PolicyInfo
	8, // 10: auth.v1.Policy.Update:output_type -> google.protobuf.Empty
	8, // 11: auth.v1.Policy.Delete:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_v1_policy_proto_init() }
func file_auth_v1_policy_proto_init() {
	if File_auth_v1_policy_proto != nil {
		return
	}
	file_auth_v1_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_policy_proto_rawDesc), len(file_auth_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_policy_proto_goTypes,
		DependencyIndexes: file_auth_v1_policy_proto_depIdxs,
		MessageInfos:      file_auth_v1_policy_proto_msgTypes,
	}.Build()
	File_auth_v1_policy_proto = out.File
	file_auth_v1_policy_proto_goTypes = nil
	file_auth_v1_policy_proto_depIdxs = nil
}
